### ISSUE TITLE
Flamethrower is broken

### ISSUE THREAD

**Issue by scroobert** [AmperSoftware/TF-Source-2#25]

**Comment by KayaDLX** [comment]
This should be fixed now, please give it a go.

**Comment by yourbadandimbest** [comment]
Range is definitely too short.

https://user-images.githubusercontent.com/91832803/203427602-caaae739-a19d-4d04-a7d6-5d116f871ca2.mp4

**Comment by yourbadandimbest** [comment]
Flames are fucked again

**Comment by Retr0-01** [comment]
This was partially fixed some weeks ago (the damage/ignite part) all that is left is the range issue.

**Comment by KayaDLX** [comment]
Is this still an issue?

**Comment by badandbest** [comment]
I believe this is still an issue.

And also, while testing, I found out that the flame particles are colliding with players instead of passing through them.

https://github.com/AmperSoftware/TF-Source-2/assets/91832803/6d5bb682-d7d1-48d5-8355-520e0af05056

**Comment by KayaDLX** [comment]
This is confirmed still being an issue
